syntax = "proto3";

package greeting;

option java_multiple_files = true;
option java_package = "com.example.grpcobservability.proto";
option java_outer_classname = "GreetingProto";

service GreetingService {
  rpc Greet (GreetRequest) returns (GreetResponse);
  rpc Farewell (FarewellRequest) returns (FarewellResponse);
  rpc GreetStream (GreetRequest) returns (stream GreetResponse);
}

message Error {
  int32 http_code = 1;
  string reason = 2;
}

message GreetRequest {
  string name = 1;
  string tenant_id = 2;
  string user_id = 3;
}

message GreetResponse {
  string message = 1;
  string request_id = 2;
  optional Error error = 3;
}

message FarewellRequest {
  string name = 1;
  string tenant_id = 2;
  string user_id = 3;
}

message FarewellResponse {
  string message = 1;
  string request_id = 2;
  optional Error error = 3;
}
