spring:
  application:
    name: grpc-observability-demo
  grpc:
    server:
      port: 9090
      observation:
        enabled: true

management:
  observations:
    annotations:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        grpc.server: true

otel:
  traces:
    exporter: otlp
  service:
    name: grpc-observability-demo
